version: '3.7'

services:
  proxy:
    image: envoyproxy/envoy:dev
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    # entrypoint: envoy -c /etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 9090:9090

  server:
    build: .
