version: '3.7'

services:
  proxy:
    image: envoyproxy/envoy:dev
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    # entrypoint: envoy -c /etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 9090:9090

  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  server:
    build: .
    environment:
      - JAEGER_AGENT_HOST=edgeproxy-test-tracing-1
      - JAEGER_AGENT_PORT=6831
